Modal
vladislavantonov-react/Restarproject pull request #5
Opened 2020-11-18 13:11 UTC by vladislavantonov-react

Modal

2020-11-18 16:39 UTC, justiceteam-it requested changes

2020-11-18 16:39 UTC, justiceteam-it commented on src/components/Modal/modal.module.scss
> +  .plus{
remove important

2020-11-18 16:39 UTC, justiceteam-it commented on src/components/Modal/Modal.jsx
> +import Row from "react-bootstrap/Row";
fix it

2020-11-18 16:39 UTC, justiceteam-it commented on src/index.js
> +  // </React.StrictMode>,
remove comments

2020-11-18 16:39 UTC, justiceteam-it commented on src/layouts/Home/Home.jsx
>  import Row from "react-bootstrap/Row";
fix it

2020-11-18 16:39 UTC, justiceteam-it commented on src/layouts/Home/Home.jsx
> +                            <ImgMediaCard title={item.title} price={item.price} img={item.img} about={item.about}/>
use column

2020-11-18 16:39 UTC, justiceteam-it commented on src/layouts/SignUp/SignUp.jsx
>  import {Container, Form, Button} from "react-bootstrap";
same

2020-11-18 16:39 UTC, justiceteam-it commented on .idea/workspace.xml
>        <change beforePath="$PROJECT_DIR$/src/components/Card/Card.jsx" beforeDir="false" afterPath="$PROJECT_DIR$/src/components/Card/Card.jsx" afterDir="false" />
remove idea dir

2020-11-18 16:39 UTC, justiceteam-it commented on src/components/Card/Card.jsx
> +import styles from "./card.module.scss";
fix it

2020-11-19 08:07 UTC, vladislavantonov-react commented on src/components/Modal/modal.module.scss
> +  .plus{
i will remove important  when i implement cart

2020-11-19 15:16 UTC, merged